### PR TITLE
jei support and levitation potion fix #1 #2

### LINKED ISSUE #1: levitation potion?

### PR DESCRIPTION
**Pull request by k1r0s**

### CODE REVIEW

**Comment by k1r0s** [comment]
no clues on JEI support but https://github.com/Shadows-of-Fire/Apotheosis have implemented it

**Comment by k1r0s** [comment]
jei support was really easy in fact https://mcforge.readthedocs.io/en/latest/advanced/accesstransformers/

**Comment by CAS-ual-TY** [comment]
Hi, I didnt see this until now unfortunately. I will implement this when I update my mods. Thank you very much (I wont merge as the code style was messed up, probably due to an automatic cleanup by your ide)

**Comment by k1r0s** [comment]
fyi i've been using this patch and working well in my server since I made the PR so u know is well headed

**Pull request closed without merging**
